<?php
global $nico_theme_name, $nico_theme, $nico_theme_positions;
$nico_theme_name = '<div style="color:#f55064;float:right;opacity:0.5;font-weight:600">&nbsp;Anne</div>';
$nico_theme = 'anne';
$nico_theme_positions = 
array(
	'menu' => 'Menu',
	'top' => 'Page top',
	'top_links' => 'Top links',
	'header' => 'Header',
	'footer_top' => 'Footer top',
	'content_top' => 'Content top',
	'content_bottom' => 'Content bottom',
	'column_left' => 'Column left',
	'column_right' => 'Column right',
	'product_tabs' => 'Product tabs (product page)',
	'below_addcart' => 'Below add to cart button (product page only)',
	'above_addcart' => 'Above add to cart button (product page only)',
	'above_desc' => 'Above description (product page only)',
);

$nico_import_stores = 
array(
	'anne.nicolette.ro' => 'anne',
	'anne2.nicolette.ro' => 'anne 2',
);

/*'nico_image_cropresize_category.ocmod.xml',*/ 
$ocmods_ignore = array('persistent_cart.ocmod.xml', 'nico_image_cropresize.ocmod.xml', 'nico_image_resizewidth.ocmod.xml','nico_image_cropresize_product.ocmod.xml', 'nico_image_resizewidth_category.ocmod.xml', 'nico_image_resizewidth_product.ocmod.xml');
